image: gitpod/workspace-dotnet   
# image: gitpod/workspace-dotnet-vnc
# port 6080, https://www.gitpod.io/docs/introduction/languages/dotnet

tasks:
  - name : Terminal Python
    before : |
      sudo apt-get update -y
      pip install --upgrade pip
      pip install beautifulsoup4
      pip install pandas
      pip install requests
      pip install lxml
      pip install flask
      pip install coolprop
      
    init: |
      echo 'TODO: build project'
      sudo apt-get install -y fonts-naver-d2coding
      pyenv install 3.9.13 && pyenv global 3.9.13 && pyenv local 3.9.13
    command: |
      echo 'TODO: start app'
      echo 'DONE: settings for Sogogi'
      pyenv global 3.9.13 && pyenv local 3.9.13

  - name: Terminal Dotnet Restore & Build
    before: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build

  - name: WASM pre-requisite
    before : |
      wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      sudo dpkg -i packages-microsoft-prod.deb
      rm packages-microsoft-prod.deb
      sudo apt-get update && \
      sudo apt-get install -y dotnet-sdk-7.0
      sudo dotnet workload install wasm-tools

    command: |
      sudo dotnet workload install wasm-experimental
      sudo dotnet new wasmbrowser
      sudo dotnet workload restore

vscode:
  extensions:
    - GrapeCity.gc-excelviewer
    - ms-toolsai.jupyter
    - ritwickdey.LiveServer
    - PKief.material-icon-theme
    - ms-python.python
    - formulahendry.code-runner
    - rangav.vscode-thunder-client